### ISSUE TITLE
Process Name

### ISSUE THREAD

**Issue by gabriel-maxx** [LiamAs05/Process-Hiding-Driver#1]
hello could you help me, I would like to know what I have to edit in the code to hide a process by name instead of PID for example:
find the process named test.exe and hide it.

**Comment by LiamAs05** [comment]
Sure! to do so, modify the function that prints all processes. Make it return once the process name is equal to the one you want.

The return value should be the PID of the process and them just pass it to HideProcess.

Add something like
```c
if (!strcmp(current,target)) {
    return pid;
}

and then call
HideProcess(pid);
```

Of course this is very abstract but should also be very straight forward to implement.

**Comment by gabriel-maxx** [comment]
@LiamAs05 thanks for answering
