### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabriel-maxx** [LiamAs05/Process-Hiding-Driver#2]
hello, I compiled the driver and tested it on windows 7 pro x64 and windows 11 enterprise x64 (10.0.22621.1344)  and when i start the driver i got a blue screen with the error "SYSTEM THREAD EXCEPTION NOT HANDLED" both machines were with the test mode activated so I can load the driver, do you know how I solve this error?

**Comment by LiamAs05** [comment]
Did you make sure the kernel versions matched? It might affect the offsets of the EPROCESS struct, leading to read/write on unintended memory in the kernel

**Comment by gabriel-maxx** [comment]
> Did you make sure the kernel versions matched? It might affect the offsets of the EPROCESS struct, leading to read/write on unintended memory in the kernel

what do i have to do to know if the kernel versions match?

**Comment by LiamAs05** [comment]
I explained it in the README section, the easiest thing to do is check the offsets of the EPROCESS struct against the ones inside the code.

**Comment by gabriel-maxx** [comment]
> I explained it in the README section, the easiest thing to do is check the offsets of the EPROCESS struct against the ones inside the code.

sorry, I'm new to this stuff, I typed "dt nt! _eprocess" in windbg kernel local debug, but what values ​​should I find? Those ones ? 

#define ListEntryOffset 
#define PidOffset 
#define NameOffset 
#define ThreadListOffset

**Comment by LiamAs05** [comment]
Yes, these ones, make sure the match the windbg output.
I really should upgrade this driver, sadly haven't had too much time to work on it.

**Comment by gabriel-maxx** [comment]
> Yes, these ones, make sure the match the windbg output. I really should upgrade this driver, sadly haven't had too much time to work on it.

it worked but there is a problem, I added the offset from the latest version of windows 11 but it doesn't work with previous versions, how do I add the offset from multiple versions of windows? I want it to be compatible with multiple versions

**Comment by LiamAs05** [comment]
I'm actually not sure, you can try to define a switch case by kernel version but I wouldn't know how to implement something like this

**Comment by gabriel-maxx** [comment]
> I'm actually not sure, you can try to define a switch case by kernel version but I wouldn't know how to implement something like this

thank you for all your knowledge
